param(
  [Parameter(Mandatory=$true)]
  [string[]]$SourcePaths,

  [Parameter(Mandatory=$false)]
  [string]$OutputDir = ".\memory\knowledge-base",

  [Parameter(Mandatory=$false)]
  [int]$MaxFilesPerSource = 5000
)

$ErrorActionPreference = "Stop"

$skipDirPattern = "\\(\.git|\.svn|\.hg|node_modules|\.pnpm|\.yarn|\.next|\.nuxt|vcpkg|build|dist|out|bin|obj|coverage|Release|Debug|\.venv|venv|__pycache__|\.pytest_cache|\.cache|logs|tmp|temp)\\"
$skipExtensions = @( ".bak", ".db", ".wal", ".shm", ".obj", ".exe", ".dll", ".log", ".pack", ".idx", ".rev" )
$doNotImportPattern = "api_token|oauth|secret|credential|password|token\.txt"
$textExtensions = @(
  ".md", ".txt", ".json", ".ps1", ".py", ".js", ".ts", ".cpp", ".hpp", ".h",
  ".cmake", ".proto", ".html", ".css", ".yml", ".yaml"
)

function Get-Category {
  param([string]$Path, [string]$Extension)

  $p = $Path.ToLowerInvariant()
  if ($p -match $doNotImportPattern) { return "do-not-import" }
  if ($p -match "office_bridge") { return "office-bridge" }
  if ($p -match "browser|cdp|extension") { return "browser-bridge" }
  if ($p -match "living_silicon|silicon") { return "control-engine" }
  if ($p -match "\\docs\\|readme|walkthrough|audit|inventory") { return "documentation" }
  if ($p -match "\\configs?\\|\.json$|\.ya?ml$") { return "configuration" }
  if ($p -match "\\scripts\\|\.ps1$") { return "automation" }
  if ($p -match "\\agents\\|_agents|workflows|skills") { return "agent-workflow" }
  if ($p -match "\\tests?\\|regression|smoke|test") { return "verification" }
  if ($p -match "\\src\\|\\tools\\|\.cpp$|\.hpp$|\.h$") { return "runtime-code" }
  return "other"
}

function Get-Relevance {
  param([string]$Category, [string]$Path)

  $p = $Path.ToLowerInvariant()
  if ($Category -eq "do-not-import") { return "blocked" }
  if ($p -match "tools_schema|runtime\.example|architecture|supervisor|work_order|bridge|health|doctor|validate") { return "high" }
  if ($Category -in @("documentation", "agent-workflow", "configuration", "automation", "verification")) { return "high" }
  if ($Category -in @("browser-bridge", "office-bridge", "control-engine")) { return "medium" }
  if ($Category -eq "runtime-code") { return "medium" }
  return "low"
}

New-Item -ItemType Directory -Force -Path $OutputDir | Out-Null

$timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
$jsonPath = Join-Path $OutputDir "knowledge-scan-$timestamp.json"
$mdPath = Join-Path $OutputDir "knowledge-scan-$timestamp.md"

$all = @()

foreach ($source in $SourcePaths) {
  if (-not (Test-Path -LiteralPath $source)) {
    $all += [pscustomobject]@{
      source = $source
      path = $source
      name = ""
      extension = ""
      size = 0
      category = "missing"
      relevance = "none"
      note = "Source path does not exist"
    }
    continue
  }

  $files = Get-ChildItem -LiteralPath $source -Recurse -File -Force -ErrorAction SilentlyContinue |
    Where-Object { $_.FullName.Replace('/', '\') -notmatch $skipDirPattern } |
    Where-Object { $_.FullName.Replace('/', '\') -notmatch '\\memory\\knowledge-base\\' } |
    Where-Object { $skipExtensions -notcontains $_.Extension.ToLowerInvariant() } |
    Where-Object { $_.Length -le 1048576 } |
    Select-Object -First $MaxFilesPerSource

  foreach ($file in $files) {
    $ext = $file.Extension.ToLowerInvariant()
    $category = Get-Category -Path $file.FullName -Extension $ext
    $relevance = Get-Relevance -Category $category -Path $file.FullName
    $isText = $textExtensions -contains $ext

    $all += [pscustomobject]@{
      source = $source
      path = $file.FullName
      name = $file.Name
      extension = $ext
      size = $file.Length
      lastWriteTime = $file.LastWriteTime.ToString("s")
      category = $category
      relevance = $relevance
      isText = $isText
    }
  }
}

$all | ConvertTo-Json -Depth 6 | Set-Content -LiteralPath $jsonPath -Encoding UTF8

$high = $all | Where-Object { $_.relevance -eq "high" }
$blocked = $all | Where-Object { $_.relevance -eq "blocked" }
$byCategory = $all | Group-Object category | Sort-Object Count -Descending
$bySource = $all | Group-Object source | Sort-Object Name

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("# Knowledge Scan $timestamp")
$lines.Add("")
$lines.Add("Generated by ``scripts/Scan-KnowledgeSources.ps1``.")
$lines.Add("")
$lines.Add("## Sources")
foreach ($g in $bySource) { $lines.Add("- ``" + $g.Name + "`` - " + $g.Count + " files") }
$lines.Add("")
$lines.Add("## Categories")
foreach ($g in $byCategory) { $lines.Add("- ``" + $g.Name + "`` - " + $g.Count) }
$lines.Add("")
$lines.Add("## High-Relevance Files")
foreach ($item in ($high | Sort-Object category,path)) {
  $lines.Add("- [" + $item.category + "] ``" + $item.path + "`` (" + $item.size + " bytes)")
}
$lines.Add("")
$lines.Add("## Do Not Import")
foreach ($item in ($blocked | Sort-Object path)) {
  $lines.Add("- ``" + $item.path + "``")
}
$lines.Add("")
$lines.Add("## Recommended Import Buckets")
$lines.Add("- ``docs/research/`` - architecture, audit, inventory, bridge notes.")
$lines.Add("- ``config/`` - sanitized runtime examples and tool schema extracts.")
$lines.Add("- ``scripts/`` - read-only scanners, validators, work-board helpers.")
$lines.Add("- ``work-orders/`` - JSON task queue model inspired by V26 team tools.")
$lines.Add("- ``memory/knowledge-base/`` - generated scan outputs and curated summaries.")

$lines | Set-Content -LiteralPath $mdPath -Encoding UTF8

Write-Host "Wrote JSON: $jsonPath"
Write-Host "Wrote Markdown: $mdPath"


